### ISSUE TITLE
Entities not available

### ISSUE THREAD

**Issue by tornbyelectrons** [HrGaertner/HA-vent-optimization#21]
Ne newly created entity is not available in HA.

Log shows issues with state having mixture of float and string. Looking at the code the state can have indeed multiple value types depending on the condition. Am I doing something wrong?

I'm on version 0.7.0

Logger: homeassistant
Source: components/sensor/__init__.py:595
First occurred: 15:42:13 (399 occurrences)
Last logged: 22:12:28

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 591, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '∞'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 717, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 808, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 752, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 595, in state
    raise ValueError(
ValueError: Sensor sensor.vent_optimization_time_wohnzimmer has device class 'None', state class 'None' unit 'min' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '∞' (<class 'str'>)

**Comment by HrGaertner** [comment]
You are right. I thought that was an clever solution to indicate that the venting will not have any effect in the moment. If you get this it means that the outside absolute humidity is greater than your absolute humidity inside, rendering venting useless for the moment. The correct way until now would have been to set it to unavailable but this was [forbidden](https://github.com/home-assistant/core/pull/98110) just a few weeks ago.

I am myself not very familiar with the Home Assistant internals. Should the desired behaviour be to set the venting time to zero and maybe add some explanation as a 'caption' or whatever Home Assistant overs additional to the sensor? What do you think

**Comment by tornbyelectrons** [comment]
Like you suggested sounds cool. I'm not an expert on HA but would think having the time for venting just as a number will do it. If no venting is needed stick to zero.  
Adding an additional status could help for understanding why venting is recommended or not. In my case i will use the number for feeding an automation process. Thank you for creating the integration:)

I'm thinking about how much further this could get: Suggestions based on temperature history and weather forecast when to vent.

**Comment by HrGaertner** [comment]
So i did not find out how i can do the additional status without creating a completely new sensor. I might do that in the future but in the moment i do not have enough time, for the Home-Assistant side of this integration i mostly copy and pasted and tried to understand what i copy and pasted (helpfully there was an integration similar to this one the home assistant side already existing). But i have a branch which should at least stop the crashing. I'll test it and the  i can merge it
