### ISSUE TITLE
weather integration

### ISSUE THREAD

**Issue by cova-fe** [HrGaertner/HA-vent-optimization#4]
Hi, I just started to play around with this integration and my issue is that I don't have any external sensor for temperature and humidity.
With HA is however possible to use weather sources to get the external data , like it is done here:
https://github.com/KartoffelToby/better_thermostat/tree/master/custom_components/better_thermostat

Have you any plan to add a similar feature? I can have a shot at it, byt my Python knowledge is pretty marginal :)

**Comment by HrGaertner** [comment]
Hello, 
i actually thought about implementing this feature, but you can relatively easily use templating to get an entity for you temperature and humidity derrived from a weather provider. Like this:

`sensor:
  - platform: template
    sensors: 
      weather_home_temp:
        value_template: "{{ state_attr('weather.home', 'temperature') }}"
        friendly_name: 'temperature_ext'
        unit_of_measurement: 'c°'`

Have a look at [this thread](https://community.home-assistant.io/t/get-humidity-from-weather-platform/274839) for more information.

Do you think this is sufficient? If not so i will consider adding support sepcifically for weather_provide entitys

**Comment by cova-fe** [comment]
> Hello, i actually thought about implementing this feature, but you can relatively easily use templating to get an entity for you temperature and humidity derrived from a weather provider. Like this:
>
> Do you think this is sufficient? If not so i will consider adding support sepcifically for weather_provide entitys

Right,  I hadn't thought about templating. I will have a try at it, If I fail I will report back :).

thanks for the hint!
